<?php
/* @var $url string */
/* @var $formName string */
/* @var $fields array */
/* @var $fieldsets array */
/* @var $hidden_fields array */
/* @var $actions array */
/* @var $helper_actions array */
/* @var $timestamp int */
/* @var $versionList array */
/* @var $version string */
/* @var $isNew boolean */
?>
<style>
.datepicker{z-index:1151 !important;}
</style>
<form class="form-horizontal form-compact" role="form" action="<?= $url ?>" name="<?= $formName ?>" method="post">
   <div class="box box-solid box-primary">
      <div class="box-header with-border">
         <h3 class="box-title">Информация о сотруднике</h3>
         <div class="box-tools pull-right">
            <?php if (!$isNew): ?>
            <div class="btn-group btn-group-sm">
               <a class="btn btn-info" data-toggle="modal" href="#historyDateModal"><i class="fa fa-clock-o"></i> <?= $timestamp ? date('d-m-Y H:i:s',$timestamp) : 'Просмотр на дату'; ?></a>
               <?php if (count($versionList)>0): ?>
               <button data-toggle="dropdown" class="btn btn-info dropdown-toggle" type="button" aria-expanded="false">
                  <span class="caret"></span>
                  <span class="sr-only">Toggle Dropdown</span>
               </button>
               <ul class="dropdown-menu pull-right scrollable-menu form-versions" role="menu">
                  <?php foreach($versionList as $k=>$v): ?>
                     <?php if ($k==$version): ?>
                        <li><a role="menuitem" href="<?= $url ?>"><?= $k.': '.date('d-m-Y H:i:s',$v).' (Текущая версия)' ?></a></li>
                     <?php else: ?>
                        <li><a role="menuitem" href="<?= $url.'?time='.$v ?>"><?= $k.': '.date('d-m-Y H:i:s',$v) ?></a></li>
                     <?php endif; ?>
                  <?php endforeach; ?>
               </ul>
               <?php endif; ?>
            </div>
            <?php endif; ?>
            <?php if (!$timestamp): ?>
               <?= $helper_actions['history']['html'] ?>
            <?php endif; ?>
         </div><!-- /.box-tools -->
      </div><!-- /.box-header -->
           <div class="box-body">
               <div class="form-group form-group-sm <?= 0 == $fields['type']['renderMode'] ? ' hide' : '' ?><?= $fields['type']['error'] ? ' has-error' : '' ?>">
                   <label class="col-sm-4 control-label" for="type"><?= $fields['type']['label'] ?></label>
                   <div class="col-sm-8">
                       <?= $fields['type']['html'] ?>
                       <?php if ($fields['type']['error']): ?><span class="help-block"><?= $fields['type']['error'] ?></span><?php endif; ?>
                   </div>
               </div>
               <div class="form-group form-group-sm <?= 0 == $fields['name']['renderMode'] ? ' hide' : '' ?><?= $fields['name']['error'] ? ' has-error' : '' ?>">
                   <label class="col-sm-4 control-label" for="name"><?= $fields['name']['label'] ?></label>
                   <div class="col-sm-8">
                       <?= $fields['name']['html'] ?>
                       <?php if ($fields['name']['error']): ?><span class="help-block"><?= $fields['name']['error'] ?></span><?php endif; ?>
                   </div>
               </div>

               <div class="box box-solid box-info">
                   <div class="box-header with-border">
                       <h3 class="box-title">Атрибуты </h3>
                   </div><!-- /.box-header -->
                   <div class="box-body">

                   </div>
               </div>
           </div><!-- /.box-body -->
       <!-- Actions Действия -->
       <div class="box-footer">
           <?= $actions['save']['html'] ?>
           <?= $actions['saveexit']['html'] ?>
           <?= $actions['exit']['html'] ?>
       </div>

       <!-- Скрытые поля -->
       <?= $hidden_fields['action']['html'] ?>
   </div>
</form>
<div class="modal" id="historyDateModal">
   <div class="modal-dialog">
      <form role="form" method="post" action="<?= $url ?>">
         <div class="modal-content">
            <div class="modal-header">
               <button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">&times;</span></button>
               <h4 class="modal-title">Выбор даты</h4>
            </div>
            <div class="modal-body">
               <div class="input-group date margin" data-provide="datepicker" data-date-format="dd-mm-yyyy" data-date-clear-btn="true" data-date-language="ru" data-date-today-highlight="true" data-date-autoclose="true">
               <input type="text" class="form-control" name="time" value="<?= $timestamp?date('d-m-Y',$timestamp):'' ?>"/>
               <span class="input-group-addon"><i class="fa fa-calendar"></i></span></div>
            </div>
            <div class="modal-footer">
               <a class="btn btn-default pull-left" href="<?= $url ?>">Сбросить</a>
               <button class="btn btn-primary" type="submit" value="save">Выбрать</button>
            </div>
         </div>
      </form>
   </div>
</div>
<script type="text/javascript">


   $('#form\\:phone').keypress(function (e) {
      var txt = String.fromCharCode(e.which);
      if (e.which !== 0 && e.which !== 8) {
         if ((txt.match(/[A-Za-zа-яА-Я.№:;,\/' @#$%^&_="?!\\]/)) || ($('#form\\:phone').val().length >= 25)) {
            return false;
         }
      }
   });

   $('#form\\:fax').keypress(function (e) {
      var txt = String.fromCharCode(e.which);
      if (e.which !== 0 && e.which !== 8) {
         if ((txt.match(/[A-Za-zа-яА-Я.№:;,\/' @#$%^&_="?!\\]/)) || ($('#form\\:fax').val().length >= 25)) {
            return false;
         }
      }
   });

   $('#form\\:email').keypress(function (e) {
      var txt = String.fromCharCode(e.which);
      if (e.which !== 0 && e.which !== 8) {
         if ((txt.match(/[а-яА-Я]/)) || ($('#form\\:email').val().length >= 40)) {
            return false;
         }
      }
   });

</script>
<?php if (isset($isValid)): ?>
   <script>
      $(document).ready(function() {
         $('#errormodal').modal() ;
      });
   </script>
<?php endif; ?>

<div id="errormodal" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title" style="text-align:center;"> Запись не сохранена! </h3>
            </div>
            <div class="modal-body">
                <h4 style="color:red; text-align:center;">Не все обязательные поля заполнены корректно.</h4>
                <hr>
                <p style="text-align:center;">* Для сохранения записи заполните поля, выделенные красным цветом, и повторно нажмите кнопку "Сохранить" </p>
            </div>
        </div>
    </div>
</div>