<?php
/* @var $url string */
/* @var $formName string */
/* @var $fields array */
/* @var $fieldsets array */
/* @var $hidden_fields array */
/* @var $actions array */
/* @var $helper_actions array */
/* @var $timestamp int */
/* @var $versionList array */
/* @var $version string */
/* @var $isNew boolean */
?>
<style>
    .datepicker{z-index:1151 !important;}
</style>
<form class="form-horizontal form-compact" role="form" action="<?= $url ?>" name="<?= $formName ?>" method="post" enctype="multipart/form-data">
    <?php if ($stateInfo): ?>
        <!-- Блок статуса подписи  -->
        <div class="box box-solid collapsed-box sign-info <?= $stateInfo['cssClass'] ?>">
            <div class="box-header with-border">
                <h3 class="box-title"><i class="fa fa-hourglass-start" aria-hidden="true"></i> Текущий статус: <?= $stateInfo['statusName'] ?></h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                </div><!-- /.box-tools -->
            </div><!-- /.box-header -->
            <div class="box-body">
                <div class="box-body table-responsive no-padding">
                    <table id="history" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Параметр</th>
                            <th>Значение</th>
                            <th>Дата</th>
                            <th>Инициатор</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($hist as $v): ?>
                            <tr class="<?= $v['form']; ?>">
                                <td><?= $v['label']; ?></td>
                                <td><?= $v['value']; ?></td>
                                <td><?= $v['mdate']; ?></td>
                                <td><?= $v['musername']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    <?php endif; ?>
    <div class="box box-solid box-primary">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-black-tie" aria-hidden="true"></i> <?= $title ?></h3>
            <div class="box-tools pull-right">
                <?php if (!$isNew): ?>
                    <div class="btn-group btn-group-sm">
                        <a class="btn btn-info" data-toggle="modal" href="#historyDateModal"><i class="fa fa-clock-o"></i> <?= $timestamp ? date('d-m-Y H:i:s',$timestamp) : 'Просмотр на дату'; ?></a>
                        <?php if (count($versionList)>0): ?>
                            <button data-toggle="dropdown" class="btn btn-info dropdown-toggle" type="button" aria-expanded="false">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu pull-right scrollable-menu form-versions" role="menu">
                                <?php foreach($versionList as $k=>$v): ?>
                                    <?php if ($k==$version): ?>
                                        <li><a role="menuitem" href="<?= $url ?>"><?= $k.': '.date('d-m-Y H:i:s',$v).' (Текущая версия)' ?></a></li>
                                    <?php else: ?>
                                        <li><a role="menuitem" href="<?= $url.'?time='.$v ?>"><?= $k.': '.date('d-m-Y H:i:s',$v) ?></a></li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
                <?php if (!$timestamp): ?>
                    <?= $helper_actions['history']['html'] ?>
                <?php endif; ?>
            </div><!-- /.box-tools -->
        </div><!-- /.box-header -->
        <div class="box-body">
            <!-- Fields Поля -->
            <div class="form-group form-group-sm <?= 0 == $fields['type']['renderMode'] ? ' hide' : '' ?><?= $fields['type']['error'] ? ' has-error' : '' ?>">
                <label class="col-sm-4 control-label" for="<?= $fields['type']['id'] ?>"><?= $fields['type']['label'] ?><?= $fields['type']['required'] ? '*' : '' ?></label>
                <div class="col-sm-8">
                    <?= $fields['type']['html'] ?>
                    <?php if ($fields['type']['error']): ?><span class="help-block"><?= $fields['type']['error'] ?></span><?php endif; ?>
                    <small id="help_<?= $fields['type']['id'] ?>" class="form-text text-muted"><?= $fields['type']['hint'] ?></small>
                </div>
            </div>
            <div class="form-group form-group-sm <?= 0 == $fields['author']['renderMode'] ? ' hide' : '' ?><?= $fields['author']['error'] ? ' has-error' : '' ?>">
                <label class="col-sm-4 control-label" for="<?= $fields['author']['id'] ?>"><?= $fields['author']['label'] ?><?= $fields['author']['required'] ? '*' : '' ?></label>
                <div class="col-sm-8">
                    <?= $fields['author']['html'] ?>
                    <?php if ($fields['author']['error']): ?><span class="help-block"><?= $fields['author']['error'] ?></span><?php endif; ?>
                    <small id="help_<?= $fields['author']['id'] ?>" class="form-text text-muted"><?= $fields['author']['hint'] ?></small>
                </div>
            </div>
            <div class="form-group form-group-sm <?= 0 == $fields['signer']['renderMode'] ? ' hide' : '' ?><?= $fields['signer']['error'] ? ' has-error' : '' ?>">
                <label class="col-sm-4 control-label"
                       for="<?= $fields['signer']['id'] ?>"><?= $fields['signer']['label'] ?><?= $fields['signer']['required'] ? '*' : '' ?></label>
                <div class="col-sm-8"><?= $fields['signer']['html'] ?><?php if ($fields['signer']['error']): ?><span class="help-block"><?= $fields['signer']['error'] ?></span><?php endif; ?>
                    <small id="help_<?= $fields['signer']['id'] ?>"class="form-text text-muted"><?= $fields['signer']['hint'] ?></small>
                </div>
            </div>

            <div class="box box-solid box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Основная информация</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div class="form-group form-group-sm <?= 0 == $fields['time_in']['renderMode'] ? ' hide' : '' ?><?= $fields['time_in']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['time_in']['id'] ?>"><?= $fields['time_in']['label'] ?><?= $fields['time_in']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['time_in']['html'] ?>
                            <?php if ($fields['time_in']['error']): ?><span class="help-block"><?= $fields['time_in']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['time_in']['id'] ?>" class="form-text text-muted"><?= $fields['time_in']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm <?= 0 == $fields['time_out']['renderMode'] ? ' hide' : '' ?><?= $fields['time_out']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['time_out']['id'] ?>"><?= $fields['time_out']['label'] ?><?= $fields['time_out']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['time_out']['html'] ?>
                            <?php if ($fields['time_out']['error']): ?><span class="help-block"><?= $fields['time_out']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['time_out']['id'] ?>" class="form-text text-muted"><?= $fields['time_out']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm <?= 0 == $fields['name']['renderMode'] ? ' hide' : '' ?><?= $fields['name']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['name']['id'] ?>"><?= $fields['name']['label'] ?><?= $fields['name']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['name']['html'] ?>
                            <?php if ($fields['name']['error']): ?><span class="help-block"><?= $fields['name']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['name']['id'] ?>" class="form-text text-muted"><?= $fields['name']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm <?= 0 == $fields['places']['renderMode'] ? ' hide' : '' ?><?= $fields['places']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['places']['id'] ?>"><?= $fields['places']['label'] ?><?= $fields['places']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['places']['html'] ?>
                            <?php if ($fields['places']['error']): ?><span class="help-block"><?= $fields['places']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['places']['id'] ?>" class="form-text text-muted"><?= $fields['places']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm <?= 0 == $fields['departments']['renderMode'] ? ' hide' : '' ?><?= $fields['departments']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['departments']['id'] ?>"><?= $fields['departments']['label'] ?><?= $fields['departments']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['departments']['html'] ?>
                            <?php if ($fields['departments']['error']): ?><span class="help-block"><?= $fields['departments']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['departments']['id'] ?>" class="form-text text-muted"><?= $fields['departments']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm <?= 0 == $fields['category']['renderMode'] ? ' hide' : '' ?><?= $fields['category']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['category']['id'] ?>"><?= $fields['category']['label'] ?><?= $fields['category']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['category']['html'] ?>
                            <?php if ($fields['category']['error']): ?><span class="help-block"><?= $fields['category']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['category']['id'] ?>" class="form-text text-muted"><?= $fields['category']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm <?= 0 == $fields['subcategory']['renderMode'] ? ' hide' : '' ?><?= $fields['subcategory']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['subcategory']['id'] ?>"><?= $fields['subcategory']['label'] ?><?= $fields['subcategory']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['subcategory']['html'] ?>
                            <?php if ($fields['subcategory']['error']): ?><span class="help-block"><?= $fields['subcategory']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['subcategory']['id'] ?>" class="form-text text-muted"><?= $fields['subcategory']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm region_partners <?= 0 == $fields['region_partners']['renderMode'] ? ' hide' : '' ?><?= $fields['region_partners']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['region_partners']['id'] ?>"><?= $fields['region_partners']['label'] ?><?= $fields['region_partners']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['region_partners']['html'] ?>
                            <?php if ($fields['region_partners']['error']): ?><span class="help-block"><?= $fields['region_partners']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['region_partners']['id'] ?>" class="form-text text-muted"><?= $fields['region_partners']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm <?= 0 == $fields['teachers']['renderMode'] ? ' hide' : '' ?><?= $fields['teachers']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['teachers']['id'] ?>"><?= $fields['teachers']['label'] ?><?= $fields['teachers']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['teachers']['html'] ?>
                            <?php if ($fields['teachers']['error']): ?><span class="help-block"><?= $fields['teachers']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['teachers']['id'] ?>" class="form-text text-muted"><?= $fields['teachers']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm <?= 0 == $fields['form_partic']['renderMode'] ? ' hide' : '' ?><?= $fields['form_partic']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['form_partic']['id'] ?>"><?= $fields['form_partic']['label'] ?><?= $fields['form_partic']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['form_partic']['html'] ?>
                            <?php if ($fields['form_partic']['error']): ?><span class="help-block"><?= $fields['form_partic']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['form_partic']['id'] ?>" class="form-text text-muted"><?= $fields['form_partic']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm form_partic <?= 0 == $fields['partic_price']['renderMode'] ? ' hide' : '' ?><?= $fields['partic_price']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['partic_price']['id'] ?>"><?= $fields['partic_price']['label'] ?><?= $fields['partic_price']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['partic_price']['html'] ?>
                            <?php if ($fields['partic_price']['error']): ?><span class="help-block"><?= $fields['partic_price']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['partic_price']['id'] ?>" class="form-text text-muted"><?= $fields['partic_price']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm <?= 0 == $fields['visit_poss']['renderMode'] ? ' hide' : '' ?><?= $fields['visit_poss']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['visit_poss']['id'] ?>"><?= $fields['visit_poss']['label'] ?><?= $fields['visit_poss']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['visit_poss']['html'] ?>
                            <?php if ($fields['visit_poss']['error']): ?><span class="help-block"><?= $fields['visit_poss']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['visit_poss']['id'] ?>" class="form-text text-muted"><?= $fields['visit_poss']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm visit_poss <?= 0 == $fields['poss_content']['renderMode'] ? ' hide' : '' ?><?= $fields['poss_content']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['poss_content']['id'] ?>"><?= $fields['poss_content']['label'] ?><?= $fields['poss_content']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['poss_content']['html'] ?>
                            <?php if ($fields['poss_content']['error']): ?><span class="help-block"><?= $fields['poss_content']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['poss_content']['id'] ?>" class="form-text text-muted"><?= $fields['poss_content']['hint'] ?></small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box box-solid box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Дополнительная информация</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div class="form-group form-group-sm <?= 0 == $fields['description']['renderMode'] ? ' hide' : '' ?><?= $fields['description']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['description']['id'] ?>"><?= $fields['description']['label'] ?><?= $fields['description']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['description']['html'] ?>
                            <?php if ($fields['description']['error']): ?><span class="help-block"><?= $fields['description']['error'] ?></span><?php endif; ?>
                            <span class="help-block" style="color: green" id="count_<?= $fields['description']['id'] ?>"></span>
                            <small id="help_<?= $fields['description']['id'] ?>" class="form-text text-muted"><?= $fields['description']['hint'] ?></small>

                        </div>
                    </div>
                    <div class="form-group form-group-sm <?= 0 == $fields['rider']['renderMode'] ? ' hide' : '' ?><?= $fields['rider']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['rider']['id'] ?>"><?= $fields['rider']['label'] ?><?= $fields['rider']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['rider']['html'] ?>
                            <?php if ($fields['rider']['error']): ?><span class="help-block"><?= $fields['rider']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['rider']['id'] ?>" class="form-text text-muted"><?= $fields['rider']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm <?= 0 == $fields['site_url']['renderMode'] ? ' hide' : '' ?><?= $fields['site_url']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['site_url']['id'] ?>"><?= $fields['site_url']['label'] ?><?= $fields['site_url']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['site_url']['html'] ?>
                            <?php if ($fields['site_url']['error']): ?><span class="help-block"><?= $fields['site_url']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['site_url']['id'] ?>" class="form-text text-muted"><?= $fields['site_url']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm <?= 0 == $fields['site_media']['renderMode'] ? ' hide' : '' ?><?= $fields['site_media']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['site_media']['id'] ?>"><?= $fields['site_media']['label'] ?><?= $fields['site_media']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['site_media']['html'] ?>
                            <?php if ($fields['site_media']['error']): ?><span class="help-block"><?= $fields['site_media']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['site_media']['id'] ?>" class="form-text text-muted"><?= $fields['site_media']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm <?= 0 == $fields['afisha_file']['renderMode'] ? ' hide' : '' ?><?= $fields['afisha_file']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['afisha_file']['id'] ?>"><?= $fields['afisha_file']['label'] ?><?= $fields['afisha_file']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['afisha_file']['html'] ?>
                            <?php if ($fields['afisha_file']['error']): ?><span class="help-block"><?= $fields['afisha_file']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['afisha_file']['id'] ?>" class="form-text text-muted"><?= $fields['afisha_file']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm <?= 0 == $fields['program_file']['renderMode'] ? ' hide' : '' ?><?= $fields['program_file']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['program_file']['id'] ?>"><?= $fields['program_file']['label'] ?><?= $fields['program_file']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['program_file']['html'] ?>
                            <?php if ($fields['program_file']['error']): ?><span class="help-block"><?= $fields['program_file']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['program_file']['id'] ?>" class="form-text text-muted"><?= $fields['program_file']['hint'] ?></small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box box-solid box-primary collapsed-box applicant-container"
                 data-lastid="<?= 0 == count($fieldsets['applicant']['instances']) ? '1' : 1 + max(array_keys($fieldsets['applicant']['instances'])) ?>">
                <div class="box-header with-border">
                    <h3 class="box-title">Сведения об ответственных лицах</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                    </div><!-- /.box-tools -->
                </div><!-- /.box-header -->
                <div class="box-body">
                    <?php foreach ($fieldsets['applicant']['instances'] as $fId => $f): ?>
                        <div class="box box-info" data-id="<?= $fId ?>">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= $f['title'] ?></h3>
                                <div class="box-tools pull-right">
                                    <a class="btn btn-sm btn-sm-fix btn-info<?= $auth < 2 ? ' hidden' : '' ?>" id="applicant:<?= $fId ?>:delete" href="#">Удалить</a>
                                </div>
                            </div><!-- /.box-header -->
                            <div class="box-body">
                                <div class="form-group form-group-sm <?= 0 == $f['fields']['applicant_id']['renderMode'] ? ' hide' : '' ?><?= $f['fields']['applicant_id']['error'] ? ' has-error' : '' ?>">
                                    <label class="col-sm-4 control-label" for="lic:applicant:<?= $fId ?>:applicant_id">Преподаватель</label>
                                    <div class="col-sm-8">
                                        <?= $f['fields']['applicant_id']['html'] ?>
                                        <?php if ($f['fields']['applicant_id']['error']): ?><span class="help-block"><?= $f['fields']['applicant_id']['error'] ?></span><?php endif; ?>
                                    </div>
                                </div>
                                <div class="form-group form-group-sm">
                                    <label class="col-sm-4 control-label">Бонусы</label>
                                    <div class="col-sm-8">
                                        <div class="box box-solid box-default bonus-container" data-lastid="<?= 0 == count($fieldsets['applicant']['instances'][$fId]['fieldsets']['bonus']['instances']) ? '1' : 1 + max(array_keys($fieldsets['applicant']['instances'][$fId]['fieldsets']['bonus']['instances'])) ?>">
                                            <div class="box-body">
                                                <?php foreach ($fieldsets['applicant']['instances'][$fId]['fieldsets']['bonus']['instances'] as $bonusId => $fBonus): ?>
                                                    <div class="box box-solid box-default" data-id="<?= $bonusId ?>">
                                                        <div class="box-body">
                                                            <div class="form-group">
                                                                <div class="col-sm-7 <?= 0 == $fBonus['fields']['period']['renderMode'] ? ' hide' : '' ?><?= $fBonus['fields']['period']['error'] ? ' has-error' : '' ?>">
                                                                    <?= $fBonus['fields']['period']['html'] ?>
                                                                    <?php if ($fBonus['fields']['period']['error']): ?><span class="help-block"><?= $fBonus['fields']['period']['error'] ?></span><?php endif; ?>
                                                                </div>
                                                                <div class="col-sm-4 <?= 0 == $fBonus['fields']['bonus']['renderMode'] ? ' hide' : '' ?><?= $fBonus['fields']['bonus']['error'] ? ' has-error' : '' ?>">
                                                                    <?= $fBonus['fields']['bonus']['html'] ?>
                                                                    <?php if ($fBonus['fields']['bonus']['error']): ?><span class="help-block"><?= $fBonus['fields']['bonus']['error'] ?></span><?php endif; ?>
                                                                </div>
                                                                <div class="col-sm-1">
                                                                    <a class="btn pull-right btn-sm btn-sm-fix btn-danger<?= $auth < 2 ? ' hidden' : '' ?>" id="applicant:<?= $fId ?>:bonus:<?= $bonusId ?>:delete" href="#"><i class="fa fa-times"></i></a>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <?php endforeach; ?>
                                            </div><!-- /.box-body -->
                                            <div class="box-footer">
                                                <a class="btn btn-default<?= $auth < 2 ? ' hidden' : '' ?>" id="applicant:<?= $fId ?>:bonus:add" href="#"><i class="fa fa-plus"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                    <?php endforeach; ?>
                </div><!-- /.box-body -->
                <div class="box-footer">
                    <a class="btn btn-default<?= $auth < 2 ? ' hidden' : '' ?>" id="applicant:add" href="#">Добавить заявителя</a>
                </div>
            </div><!-- /.box -->
            <div class="box box-solid collapsed-box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Общие итоги мероприятия</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                    </div><!-- /.box-tools -->
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div class="form-group form-group-sm <?= 0 == $fields['result']['renderMode'] ? ' hide' : '' ?><?= $fields['result']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['result']['id'] ?>"><?= $fields['result']['label'] ?><?= $fields['result']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['result']['html'] ?>
                            <?php if ($fields['result']['error']): ?><span class="help-block"><?= $fields['result']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['result']['id'] ?>" class="form-text text-muted"><?= $fields['result']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm <?= 0 == $fields['num_users']['renderMode'] ? ' hide' : '' ?><?= $fields['num_users']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['num_users']['id'] ?>"><?= $fields['num_users']['label'] ?><?= $fields['num_users']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['num_users']['html'] ?>
                            <?php if ($fields['num_users']['error']): ?><span class="help-block"><?= $fields['num_users']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['num_users']['id'] ?>" class="form-text text-muted"><?= $fields['num_users']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm <?= 0 == $fields['num_winners']['renderMode'] ? ' hide' : '' ?><?= $fields['num_winners']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['num_winners']['id'] ?>"><?= $fields['num_winners']['label'] ?><?= $fields['num_winners']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['num_winners']['html'] ?>
                            <?php if ($fields['num_winners']['error']): ?><span class="help-block"><?= $fields['num_winners']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['num_winners']['id'] ?>" class="form-text text-muted"><?= $fields['num_winners']['hint'] ?></small>
                        </div>
                    </div>
                    <div class="form-group form-group-sm <?= 0 == $fields['num_visitors']['renderMode'] ? ' hide' : '' ?><?= $fields['num_visitors']['error'] ? ' has-error' : '' ?>">
                        <label class="col-sm-4 control-label" for="<?= $fields['num_visitors']['id'] ?>"><?= $fields['num_visitors']['label'] ?><?= $fields['num_visitors']['required'] ? '*' : '' ?></label>
                        <div class="col-sm-8">
                            <?= $fields['num_visitors']['html'] ?>
                            <?php if ($fields['num_visitors']['error']): ?><span class="help-block"><?= $fields['num_visitors']['error'] ?></span><?php endif; ?>
                            <small id="help_<?= $fields['num_visitors']['id'] ?>" class="form-text text-muted"><?= $fields['num_visitors']['hint'] ?></small>
                        </div>
                    </div>
                </div><!-- /.box-body -->
            </div>
        <!-- Actions Действия -->
        <div class="box-footer">
            <?= $actions['save']['html'] ?>
            <?= $actions['saveexit']['html'] ?>
            <?= $actions['exit']['html'] ?>
            <?= $actions['sign-send-modal']['html'] ?>
            <?= $actions['sign-by']['html'] ?>
            <?= $actions['sign-return-modal']['html'] ?>
            <?= $actions['make-changes']['html'] ?>
        </div>

        <!-- Скрытые поля -->
        <?= $hidden_fields['action']['html'] ?>
    </div
</form>
<div class="modal" id="historyDateModal">
    <div class="modal-dialog">
        <form role="form" method="post" action="<?= $url ?>">
            <div class="modal-content">
                <div class="modal-header">
                    <button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Выбор даты</h4>
                </div>
                <div class="modal-body">
                    <div class="input-group date margin" data-provide="datepicker" data-date-format="dd-mm-yyyy" data-date-clear-btn="true" data-date-language="ru" data-date-today-highlight="true" data-date-autoclose="true">
                        <input type="text" class="form-control" name="time" value="<?= $timestamp?date('d-m-Y',$timestamp):'' ?>"/>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span></div>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-default pull-left" href="<?= $url ?>">Сбросить</a>
                    <button class="btn btn-primary" type="submit" value="save">Выбрать</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script id="applicant-template" type="text/x-handlebars-template">
    <div class="box box-info" data-id="{{id}}">
        <div class="box-header with-border">
            <h3 class="box-title"><?= $fieldsets['applicant']['template']['title'] ?></h3>
            <div class="box-tools pull-right">
                <a class="btn btn-sm btn-sm-fix btn-info" id="applicant:{{id}}:delete" href="#">Удалить</a>
            </div>
        </div><!-- /.box-header -->
        <div class="box-body">
            <div class="form-group form-group-sm <?= 0 == $fieldsets['applicant']['template']['fields']['applicant_id']['renderMode'] ? ' hide' : '' ?>">
                <label class="col-sm-4 control-label" for="lic:applicant:{{id}}:applicant_id">Преподаватель</label>
                <div class="col-sm-8">
                    <?= $fieldsets['applicant']['template']['fields']['applicant_id']['html'] ?>
                </div>
            </div>
            <div class="form-group form-group-sm">
                <label class="col-sm-4 control-label">Бонусы</label>
                <div class="col-sm-8">
                    <div class="box box-solid box-default bonus-container" data-lastid="1">
                        <div class="box-body">
                        </div><!-- /.box-body -->
                        <div class="box-footer">
                            <a class="btn btn-default" id="applicant:{{id}}:bonus:add" data-id="{{id}}" href="#"><i class="fa fa-plus"></i></a>
                        </div>
                    </div><!-- /.box -->
                </div>
            </div>

        </div><!-- /.box-body -->
    </div><!-- /.box -->
</script>

<script id="bonus-template" type="text/x-handlebars-template">
    <div class="box box-solid box-default" data-id="{{id}}">
        <div class="box-body">
            <div class="form-group">
                <div class="col-sm-7 <?= 0 == $fieldsets['applicant']['template']['fieldsets']['bonus']['template']['fields']['period']['renderMode'] ? ' hide' : '' ?>">
                    <?= $fieldsets['applicant']['template']['fieldsets']['bonus']['template']['fields']['period']['html'] ?>
                </div>
                <div class="col-sm-4<?= 0 == $fieldsets['applicant']['template']['fieldsets']['bonus']['template']['fields']['bonus']['renderMode'] ? ' hide' : '' ?>">
                    <?= $fieldsets['applicant']['template']['fieldsets']['bonus']['template']['fields']['bonus']['html'] ?>
                </div>
                <div class="col-sm-1">
                    <a class="btn pull-right btn-sm btn-sm-fix btn-danger" id="applicant:{{parentId}}:bonus:{{id}}:delete" href="#"><i class="fa fa-times"></i></a>
                </div>
            </div>
        </div>
    </div>
</script>
<script>
    var form = {
        tmplApplicant: null,
        tmplBonus: null,
        init: function () {
            var self = this;
            this.tmplApplicant = Handlebars.compile($('#applicant-template').html());
            this.tmplBonus = Handlebars.compile($('#bonus-template').html());
            app.formInitContainer($('div.applicant-container'), 'applicant', this.tmplApplicant, {}, function(id, div) {
                self.formBonusInitContainer(id, $('div.bonus-container', div)); // Поощрения
            });

            $('input[name="f\\:form_partic"]').on('ifChecked', function () {
                self.toggleType($(this).val(), '.form_partic');
            });
            self.toggleType($('input[name="f\\:form_partic"]:checked').val(), '.form_partic');
            $('input[name="f\\:visit_poss"]').on('ifChecked', function () {
                self.toggleType($(this).val(), '.visit_poss');
            });
            self.toggleType($('input[name="f\\:visit_poss"]:checked').val(), '.visit_poss');

            // колличество символов
            document.getElementById('f:description').addEventListener("input", function () {
                document.getElementById('count_f:description').innerText = 'Введено: ' + this.value.length + ' символа(ов), включая пробелы.';
                // console.log(currentLength);
            });

            // скрываем поле Региональные партнеры
            let value = document.getElementById('f:subcategory').value;
            (value === '31' || value === '32') ? $('.region_partners').show() : $('.region_partners').hide();

            document.getElementById('f:subcategory').addEventListener("change", function () {
                (this.value === '31' || this.value === '32') ? $('.region_partners').show() : $('.region_partners').hide();
                 // console.log(this.value);
            });

            // Связанные списки
            let cat = $('#f\\:category');
            let subcat = $('#f\\:subcategory');
            let url = "<?= \yii\helpers\Url::to(['activities/subcategory-options']) ?>";
            let hint = '<option>Загрузка...</option>';
            self.depDrop(cat, subcat, url, hint);
        },
        formBonusInitContainer: function (parentId, div) {
            var self = this;
            $('#applicant\\:' + parentId + '\\:bonus\\:add', div).click(function () { // активируем кнопку добавить подраздел
                var id = div.data('lastid');
                div.children('div.box-body').append(self.tmplBonus({parentId: parentId, id: id})); // вставить шаблон
                self.formBonusInitSection(parentId, $('div.box[data-id=' + id + ']', div));
                div.data('lastid', id + 1);
                return false;
            });
            // настройка секций
            div.children('div.box-body').children('div.box').each(function (i, e) {
                self.formBonusInitSection(parentId, $(this));
            });
        },
        formBonusInitSection: function (parentId, div) {
            var self = this;
            $('#applicant\\:' + parentId + '\\:bonus\\:' + div.data('id') + '\\:delete', div).click(app.deleteSectionCallback); // активировать кнопку удалить
            app.activateFormFields(div);
        },
        toggleType: function (value, container) {
            value === '1' ? $(container).hide() : $(container).show();
        },
        depDrop: function (cat, subcat, url, hint) {
            // начальная загрузка
            subcat.attr("disabled", true);
            subcat.html(hint);
            $.ajax({
                type: "POST",
                url: url,
                data: {id: cat.val(), ids: subcat.val()},
                success: function (data) {
                    subcat.html(data);
                    subcat.attr("disabled", false);
                }
            });
            // обработка события
            cat.change(function () {
                subcat.attr("disabled", true);
                subcat.html(hint);
                $.ajax({
                    type: "POST",
                    url: url,
                    data: {id: $(this).val(), ids: subcat.val()},
                    success: function (data) {
                        subcat.html(data);
                        subcat.attr("disabled", false);
                    }
                });
            });
        }
    };
    $().ready(function () {
        form.init();
    });
</script>

<?php if (isset($isValid)): ?>
    <script>
        $(document).ready(function() {
            $('#errormodal').modal() ;
        });
    </script>
<?php endif; ?>

<div id="errormodal" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title" style="text-align:center;"> Запись не сохранена! </h3>
            </div>
            <div class="modal-body">
                <h4 style="color:red; text-align:center;">Не все обязательные поля заполнены корректно.</h4>
                <hr>
                <p style="text-align:center;">* Для сохранения записи заполните поля, выделенные красным цветом, и повторно нажмите кнопку "Сохранить" </p>
            </div>
        </div>
    </div>
</div>

<div class="modal modal-default fade in" id="signSendModal">
    <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Отправить на подпись</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group form-group-sm ">
                        <label class="col-sm-4 control-label" for="author_content">Сообщение автора</label>
                        <div class="col-sm-8"><textarea id="author_content" name="author_content" cols="40" rows="3" class="form-control"></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <?= $actions['sign-send']['html'] ?>
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Закрыть</button>
                </div>
            </div>
    </div>
</div>


<div class="modal modal-default fade in" id="signReturnModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Отправить на доработку</h4>
            </div>
            <div class="modal-body">
                <div class="form-group form-group-sm ">
                    <label class="col-sm-4 control-label" for="signer_content">Сообщение подписанта</label>
                    <div class="col-sm-8"><textarea id="signer_content" name="signer_content" cols="40" rows="3" class="form-control"></textarea>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <?= $actions['sign-return']['html'] ?>
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>