<?php
/* @var $url string */
/* @var $formName string */
/* @var $fields array */
/* @var $fieldsets array */
/* @var $hidden_fields array */
/* @var $actions array */
/* @var $helper_actions array */
?>
<form class="form-horizontal form-compact" role="form" action="<?= $url ?>" name="<?= $formName ?>" method="post" enctype="multipart/form-data">
    <div class="box box-solid box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Атрибуты аудитории</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <div class="form-group form-group-sm <?= $fields['building_id']['error'] ? ' has-error' : '' ?>">
                <label class="col-sm-4 control-label" for="building_id"><?= $fields['building_id']['label'] ?></label>
                <div class="col-sm-8">
                    <?= $fields['building_id']['html'] ?>
                    <?php if ($fields['building_id']['error']): ?><span class="help-block"><?= $fields['building_id']['error'] ?></span><?php endif; ?>
                </div>
            </div>
             <div class="form-group form-group-sm <?= $fields['cat_id']['error'] ? ' has-error' : '' ?>">
                <label class="col-sm-4 control-label" for="cat_id"><?= $fields['cat_id']['label'] ?></label>
                <div class="col-sm-8">
                    <?= $fields['cat_id']['html'] ?>
                    <?php if ($fields['cat_id']['error']): ?><span class="help-block"><?= $fields['cat_id']['error'] ?></span><?php endif; ?>
                </div>
            </div>
             <div class="form-group form-group-sm <?= $fields['study_flag']['error'] ? ' has-error' : '' ?>">
                <label class="col-sm-4 control-label" for="study_flag"><?= $fields['study_flag']['label'] ?></label>
                <div class="col-sm-8">
                    <?= $fields['study_flag']['html'] ?>
                    <?php if ($fields['study_flag']['error']): ?><span class="help-block"><?= $fields['study_flag']['error'] ?></span><?php endif; ?>
                </div>
            </div>
             <div class="form-group form-group-sm <?= $fields['num']['error'] ? ' has-error' : '' ?>">
                <label class="col-sm-4 control-label" for="num"><?= $fields['num']['label'] ?></label>
                <div class="col-sm-8">
                    <?= $fields['num']['html'] ?>
                    <?php if ($fields['num']['error']): ?><span class="help-block"><?= $fields['num']['error'] ?></span><?php endif; ?>
                </div>
            </div>
             <div class="form-group form-group-sm <?= $fields['name']['error'] ? ' has-error' : '' ?>">
                <label class="col-sm-4 control-label" for="name"><?= $fields['name']['label'] ?></label>
                <div class="col-sm-8">
                    <?= $fields['name']['html'] ?>
                    <?php if ($fields['name']['error']): ?><span class="help-block"><?= $fields['name']['error'] ?></span><?php endif; ?>
                </div>
            </div>
             <div class="form-group form-group-sm <?= $fields['floor']['error'] ? ' has-error' : '' ?>">
                <label class="col-sm-4 control-label" for="floor"><?= $fields['floor']['label'] ?></label>
                <div class="col-sm-8">
                    <?= $fields['floor']['html'] ?>
                    <?php if ($fields['floor']['error']): ?><span class="help-block"><?= $fields['floor']['error'] ?></span><?php endif; ?>
                </div>
            </div>
             <div class="form-group form-group-sm <?= $fields['area']['error'] ? ' has-error' : '' ?>">
                <label class="col-sm-4 control-label" for="area"><?= $fields['area']['label'] ?></label>
                <div class="col-sm-8">
                    <?= $fields['area']['html'] ?>
                    <?php if ($fields['area']['error']): ?><span class="help-block"><?= $fields['area']['error'] ?></span><?php endif; ?>
                </div>
            </div>
             <div class="form-group form-group-sm <?= $fields['capacity']['error'] ? ' has-error' : '' ?>">
                <label class="col-sm-4 control-label" for="capacity"><?= $fields['capacity']['label'] ?></label>
                <div class="col-sm-8">
                    <?= $fields['capacity']['html'] ?>
                    <?php if ($fields['capacity']['error']): ?><span class="help-block"><?= $fields['capacity']['error'] ?></span><?php endif; ?>
                </div>
            </div>
            <div class="form-group form-group-sm <?= $fields['description']['error'] ? ' has-error' : '' ?>">
                <label class="col-sm-4 control-label" for="description"><?= $fields['description']['label'] ?></label>
                <div class="col-sm-8">
                    <?= $fields['description']['html'] ?>
                    <?php if ($fields['description']['error']): ?><span class="help-block"><?= $fields['description']['error'] ?></span><?php endif; ?>
                </div>
            </div>

        </div><!-- /.box-body -->

        <!-- Actions Действия -->
        <div class="box-footer">
            <?= $actions['save']['html'] ?>
            <?= $actions['saveexit']['html'] ?>
            <?= $actions['exit']['html'] ?>
        </div>

        <!-- Скрытые поля -->
        <?= $hidden_fields['action']['html'] ?>
    </div>
</form>

<?php if (isset($isValid)): ?>
    <script>
        $(document).ready(function () {
            $('#errormodal').modal();
        });
    </script>
<?php endif; ?>

<div id="errormodal" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title" style="text-align:center;"> Запись не сохранена! </h3>
            </div>
            <div class="modal-body">
                <h4 style="color:red; text-align:center;">Не все обязательные поля заполнены корректно.</h4>
                <hr>
                <p style="text-align:center;">* Для сохранения записи заполните поля, выделенные красным цветом, и повторно нажмите кнопку "Сохранить" </p>
            </div>
        </div>
    </div>
</div>
