<?php
/* @var $url string */
/* @var $formName string */
/* @var $fields array */
/* @var $fieldsets array */
/* @var $hidden_fields array */
/* @var $actions array */
/* @var $helper_actions array */
/* @var $timestamp int */
/* @var $versionList array */
/* @var $version string */
/* @var $isNew boolean */
?>
<style>
    .datepicker{z-index:1151 !important;}
</style>
<form class="form-horizontal form-compact" role="form" action="<?= $url ?>" name="<?= $formName ?>" method="post" enctype="multipart/form-data">
    <div class="box box-solid box-primary">
        <div class="box-header with-border">
            <h3 class="box-title"><?= $title ?></h3>
            <div class="box-tools pull-right">
                <?php if (!$isNew): ?>
                    <div class="btn-group btn-group-sm">
                        <a class="btn btn-info" data-toggle="modal" href="#historyDateModal"><i class="fa fa-clock-o"></i> <?= $timestamp ? date('d-m-Y H:i:s',$timestamp) : 'Просмотр на дату'; ?></a>
                        <?php if (count($versionList)>0): ?>
                            <button data-toggle="dropdown" class="btn btn-info dropdown-toggle" type="button" aria-expanded="false">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu pull-right scrollable-menu form-versions" role="menu">
                                <?php foreach($versionList as $k=>$v): ?>
                                    <?php if ($k==$version): ?>
                                        <li><a role="menuitem" href="<?= $url ?>"><?= $k.': '.date('d-m-Y H:i:s',$v).' (Текущая версия)' ?></a></li>
                                    <?php else: ?>
                                        <li><a role="menuitem" href="<?= $url.'?time='.$v ?>"><?= $k.': '.date('d-m-Y H:i:s',$v) ?></a></li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
                <?php if (!$timestamp): ?>
                    <?= $helper_actions['history']['html'] ?>
                <?php endif; ?>
            </div><!-- /.box-tools -->
        </div><!-- /.box-header -->
        <div class="box-body">
            <!-- Fields Поля -->
            <?php foreach ($fields as $id => $field): ?>
                <div class="form-group form-group-sm <?= 0 == $field['renderMode'] ? ' hide' : '' ?><?= $field['error'] ? ' has-error' : '' ?>">
                    <label class="col-sm-4 control-label" for="<?= $field['id'] ?>"><?= $field['label'] ?><?= $field['required'] ? '*' : '' ?></label>
                    <div class="col-sm-8">
                        <?= $field['html'] ?>
                        <?php if ($field['error']): ?><span class="help-block"><?= $field['error'] ?></span><?php endif; ?>
                    </div>
                </div>
            <?php endforeach;?>
            <?php if (!$isNew): ?>
            <div class="box box-solid box-primary subject-container"
                 data-lastid="<?= 0 == count($fieldsets['subject']['instances']) ? '1' : 1 + max(array_keys($fieldsets['subject']['instances'])) ?>">
                <div class="box-header with-border">
                    <h3 class="box-title">Учебные дисциплины</h3>
                </div><!-- /.box-header -->
                <div class="box-body">

                    <?php foreach ($fieldsets['subject']['instances'] as $fId => $f): ?>
                        <div class="box box-solid box-info" data-id="<?= $fId ?>">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= $f['title'] ?></h3>
                                <div class="box-tools pull-right">
                                    <a class="btn btn-sm btn-sm-fix btn-info<?= $auth < 2 ? ' hidden' : '' ?>" id="subject:<?= $fId ?>:delete" href="#">Удалить</a>
                                </div>
                            </div><!-- /.box-header -->
                            <div class="box-body">
                                <div class="form-group form-group-sm <?= 0 == $f['fields']['subject_sect']['renderMode'] ? ' hide' : '' ?><?= $f['fields']['subject_sect']['error'] ? ' has-error' : '' ?>">
                                    <label class="col-sm-4 control-label" for="lic:subject:<?= $fId ?>:name"><?= $f['fields']['subject_sect']['label'] ?><?= $f['fields']['subject_sect']['required'] ? '*' : '' ?></label>
                                    <div class="col-sm-8">
                                        <?= $f['fields']['subject_sect']['html'] ?>
                                        <?php if ($f['fields']['subject_sect']['error']): ?><span class="help-block"><?= $f['fields']['subject_sect']['error'] ?></span><?php endif; ?>
                                    </div>
                                </div>
                                <div class="form-group form-group-sm <?= 0 == $f['fields']['subject']['renderMode'] ? ' hide' : '' ?><?= $f['fields']['subject']['error'] ? ' has-error' : '' ?>">
                                    <label class="col-sm-4 control-label" for="lic:subject:<?= $fId ?>:name"><?= $f['fields']['subject']['label'] ?><?= $f['fields']['subject']['required'] ? '*' : '' ?></label>
                                    <div class="col-sm-8">
                                        <?= $f['fields']['subject']['html'] ?>
                                        <?php if ($f['fields']['subject']['error']): ?><span class="help-block"><?= $f['fields']['subject']['error'] ?></span><?php endif; ?>
                                    </div>
                                </div>

                                <div class="form-group form-group-sm">
                                    <div class="col-sm-12">
                                        <table id="f:subject:<?= $fId ?>:loads" class="table table-bordered" role="grid">
                                            <thead>
                                                <tr>
                                                    <th style="text-align: center" colspan="<?= $period_study * 2?>">Вариативная часть - часов в неделю / Консультации - часов в год</th>
                                                </tr>
                                                <tr>
                                                <?php for ($i = 1; $i <= $period_study; $i++): ?>
                                                    <th style="text-align: center" colspan="2"><?= $i ?> год</th>
                                                <?php endfor; ?>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                            <?php for ($i = 1; $i <= $period_study; $i++): ?>
                                                    <td><input type="text" id="f:subject:<?= $fId ?>:loads:<?= $i ?>:week_time" name="f:subject:<?= $fId ?>:loads:<?= $i ?>:week_time" value="<?= $subject[$fId]['loads'][$i]['week_time'] ?? 0 ?>" class="form-control"></td>
                                                    <td><input type="text" id="f:subject:<?= $fId ?>:loads:<?= $i ?>:year_time" name="f:subject:<?= $fId ?>:loads:<?= $i ?>:year_time" value="<?= $subject[$fId]['loads'][$i]['year_time'] ?? 0 ?>" class="form-control">
                                                        <input type="hidden" id="f:subject:<?= $fId ?>:loads:<?= $i ?>:period" name="f:subject:<?= $fId ?>:loads:<?= $i ?>:period" value="<?= $i ?>" class="form-control"></td>
                                            <?php endfor; ?>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                    <?php endforeach; ?>
                </div><!-- /.box-body -->
                <div class="box-footer">
                    <a class="btn btn-default<?= $auth < 2 ? ' hidden' : '' ?>" id="subject:add" href="#">Добавить раздел</a>
                </div>
            </div><!-- /.box -->
            <?php endif;?>
        </div>
        <!-- Actions Действия -->
        <div class="box-footer">
            <?= $actions['save']['html'] ?>
            <?= $actions['saveexit']['html'] ?>
            <?= $actions['exit']['html'] ?>
        </div>

        <!-- Скрытые поля -->
        <?= $hidden_fields['action']['html'] ?>
    </div>
</form>
<div class="modal" id="historyDateModal">
    <div class="modal-dialog">
        <form role="form" method="post" action="<?= $url ?>">
            <div class="modal-content">
                <div class="modal-header">
                    <button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Выбор даты</h4>
                </div>
                <div class="modal-body">
                    <div class="input-group date margin" data-provide="datepicker" data-date-format="dd-mm-yyyy" data-date-clear-btn="true" data-date-language="ru" data-date-today-highlight="true" data-date-autoclose="true">
                        <input type="text" class="form-control" name="time" value="<?= $timestamp?date('d-m-Y',$timestamp):'' ?>"/>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span></div>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-default pull-left" href="<?= $url ?>">Сбросить</a>
                    <button class="btn btn-primary" type="submit" value="save">Выбрать</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script id="subject-template" type="text/x-handlebars-template">
    <div class="box box-solid box-info" data-id="{{id}}">
        <div class="box-header with-border">
            <h3 class="box-title">Предмет</h3>
            <div class="box-tools pull-right">
                <a class="btn btn-sm btn-sm-fix btn-info" id="subject:{{id}}:delete" href="#">Удалить</a>
            </div>
        </div><!-- /.box-header -->
        <div class="box-body">
            <div class="form-group form-group-sm <?= 0 == $fieldsets['subject']['template']['fields']['subject_sect']['renderMode'] ? ' hide' : '' ?>">
                <label class="col-sm-4 control-label" for="lic:subject:{{id}}:subject_sect"><?= $fieldsets['subject']['template']['fields']['subject_sect']['label'] ?></label>
                <div class="col-sm-8">
                    <?= $fieldsets['subject']['template']['fields']['subject_sect']['html'] ?>
                </div>
            </div>
            <div class="form-group form-group-sm <?= 0 == $fieldsets['subject']['template']['fields']['subject']['renderMode'] ? ' hide' : '' ?>">
                <label class="col-sm-4 control-label" for="lic:subject:{{id}}:subject"><?= $fieldsets['subject']['template']['fields']['subject']['label'] ?></label>
                <div class="col-sm-8">
                    <?= $fieldsets['subject']['template']['fields']['subject']['html'] ?>
                </div>
            </div>
            <div class="form-group form-group-sm">
                <div class="col-sm-12">
                    <table id="f:subject:{{id}}:loads" class="table table-bordered" role="grid">
                        <thead>
                        <tr>
                            <th style="text-align: center" colspan="<?= $period_study * 2?>">Вариативная часть - часов в неделю / Консультации - часов в год</th>
                        </tr>
                        <tr>
                            <?php for ($i = 1; $i <= $period_study; $i++): ?>
                                <th colspan="2"><?= $i ?> год</th>
                            <?php endfor; ?>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <?php for ($i = 1; $i <= $period_study; $i++): ?>
                                <td>
                                    <input type="text" id="f:subject:{{id}}:loads:<?= $i ?>:week_time" name="f:subject:{{id}}:loads:<?= $i ?>:week_time" value="0" class="form-control">
                                </td>
                                <td>
                                    <input type="text" id="f:subject:{{id}}:loads:<?= $i ?>:year_time" name="f:subject:{{id}}:loads:<?= $i ?>:year_time" value="0" class="form-control">
                                    <input type="hidden" id="f:subject:{{id}}:loads:<?= $i ?>:period" name="f:subject:{{id}}:loads:<?= $i ?>:period" value="<?= $i ?>" class="form-control">
                                </td>
                            <?php endfor; ?>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</script>

<script>
    var form = {
        tmplSubject: null,
       // tmplBonus: null,
        init: function () {
            var self = this;
            this.tmplSubject = Handlebars.compile($('#subject-template').html());
           // this.tmplBonus = Handlebars.compile($('#loads-template').html());
            app.formInitContainer($('div.subject-container'), 'subject', this.tmplSubject, {}, function(id, div) {
                //self.formBonusInitContainer(id, $('div.loads-container', div)); // Поощрения
            });

        }
    };
    $().ready(function () {
        form.init();
    });
</script>
<?php if (isset($isValid)): ?>
    <script>
        $(document).ready(function() {
            $('#errormodal').modal() ;
        });
    </script>
<?php endif; ?>

<div id="errormodal" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title" style="text-align:center;"> Запись не сохранена! </h3>
            </div>
            <div class="modal-body">
                <h4 style="color:red; text-align:center;">Не все обязательные поля заполнены корректно.</h4>
                <hr>
                <p style="text-align:center;">* Для сохранения записи заполните поля, выделенные красным цветом, и повторно нажмите кнопку "Сохранить" </p>
            </div>
        </div>
    </div>
</div>