<?php
/* @var $url string */
/* @var $formName string */
/* @var $fields array */
/* @var $fieldsets array */
/* @var $hidden_fields array */
/* @var $actions array */
/* @var $helper_actions array */
/* @var $timestamp int */
/* @var $versionList array */
/* @var $version string */
/* @var $isNew boolean */
?>
<style>
    .datepicker{z-index:1151 !important;}
</style>
<form class="form-horizontal form-compact" role="form" action="<?= $url ?>" name="<?= $formName ?>" method="post" enctype="multipart/form-data">

    <div class="box box-solid box-primary">
        <div class="box-header with-border">
            <h3 class="box-title"><?= $title ?></h3>
            <div class="box-tools pull-right">
                <?php if (!$isNew): ?>
                    <div class="btn-group btn-group-sm">
                        <a class="btn btn-info" data-toggle="modal" href="#historyDateModal"><i class="fa fa-clock-o"></i> <?= $timestamp ? date('d-m-Y H:i:s',$timestamp) : 'Просмотр на дату'; ?></a>
                        <?php if (count($versionList)>0): ?>
                            <button data-toggle="dropdown" class="btn btn-info dropdown-toggle" type="button" aria-expanded="false">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu pull-right scrollable-menu form-versions" role="menu">
                                <?php foreach($versionList as $k=>$v): ?>
                                    <?php if ($k==$version): ?>
                                        <li><a role="menuitem" href="<?= $url ?>"><?= $k.': '.date('d-m-Y H:i:s',$v).' (Текущая версия)' ?></a></li>
                                    <?php else: ?>
                                        <li><a role="menuitem" href="<?= $url.'?time='.$v ?>"><?= $k.': '.date('d-m-Y H:i:s',$v) ?></a></li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
                <?php if (!$timestamp): ?>
                    <?= $helper_actions['history']['html'] ?>
                <?php endif; ?>
            </div><!-- /.box-tools -->
        </div><!-- /.box-header -->
        <div class="box-body">
            <!-- Fields Поля -->
            <?php foreach ($fields as $id => $field): ?>
                <div class="form-group form-group-sm <?= 0 == $field['renderMode'] ? ' hide' : '' ?><?= $field['error'] ? ' has-error' : '' ?>">
                    <label class="col-sm-4 control-label" for="<?= $field['id'] ?>"><?= $field['label'] ?><?= $field['required'] ? '*' : '' ?></label>
                    <div class="col-sm-8">
                        <?= $field['html'] ?>
                        <?php if ($field['error']): ?><span class="help-block"><?= $field['error'] ?></span><?php endif; ?>
                    </div>
                </div>
            <?php endforeach;?>
        <div class="box box-solid box-primary subject-container"
             data-lastid="<?= 0 == count($fieldsets['subject']['instances']) ? '1' : 1 + max(array_keys($fieldsets['subject']['instances'])) ?>">
            <div class="box-header with-border">
                <h3 class="box-title">Учебные дисциплины</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <?php foreach ($fieldsets['subject']['instances'] as $fId => $f): ?>
                    <div class="box box-solid box-info" data-id="<?= $fId ?>">
                        <div class="box-header with-border">
                            <h3 class="box-title"><?= $f['title'] ?></h3>
                            <div class="box-tools pull-right">
                                <a class="btn btn-sm btn-sm-fix btn-info<?= $auth < 2 ? ' hidden' : '' ?>" id="subject:<?= $fId ?>:delete" href="#">Удалить</a>
                            </div>
                        </div><!-- /.box-header -->
                        <div class="box-body">

                            <div class="form-group form-group-sm <?= 0 == $f['fields']['subject_cat']['renderMode'] ? ' hide' : '' ?><?= $f['fields']['subject_cat']['error'] ? ' has-error' : '' ?>">
                                <label class="col-sm-4 control-label" for="lic:subject:<?= $fId ?>:name">Категория дисциплины</label>
                                <div class="col-sm-8">
                                    <?= $f['fields']['subject_cat']['html'] ?>
                                    <?php if ($f['fields']['subject_cat']['error']): ?><span class="help-block"><?= $f['fields']['subject_cat']['error'] ?></span><?php endif; ?>
                                </div>
                            </div>

                            <div class="form-group form-group-sm">
                                <label class="col-sm-4 control-label">Нагрузка</label>
                                <div class="col-sm-8">
                                    <div class="box box-solid box-default loads-container" data-lastid="<?= 0 == count($fieldsets['subject']['instances'][$fId]['fieldsets']['loads']['instances']) ? '1' : 1 + max(array_keys($fieldsets['subject']['instances'][$fId]['fieldsets']['loads']['instances'])) ?>">
                                        <div class="box-body">
                                            <?php foreach ($fieldsets['subject']['instances'][$fId]['fieldsets']['loads']['instances'] as $loadsId => $fBonus): ?>
                                                <div class="box box-solid box-default" data-id="<?= $loadsId ?>">
                                                    <div class="box-body">
                                                        <div class="form-group">
                                                            <div class="col-sm-7 <?= 0 == $fBonus['fields']['period']['renderMode'] ? ' hide' : '' ?><?= $fBonus['fields']['period']['error'] ? ' has-error' : '' ?>">
                                                                <?= $fBonus['fields']['period']['html'] ?>
                                                                <?php if ($fBonus['fields']['period']['error']): ?><span class="help-block"><?= $fBonus['fields']['period']['error'] ?></span><?php endif; ?>
                                                            </div>
                                                            <div class="col-sm-4 <?= 0 == $fBonus['fields']['bonus']['renderMode'] ? ' hide' : '' ?><?= $fBonus['fields']['bonus']['error'] ? ' has-error' : '' ?>">
                                                                <?= $fBonus['fields']['bonus']['html'] ?>
                                                                <?php if ($fBonus['fields']['bonus']['error']): ?><span class="help-block"><?= $fBonus['fields']['bonus']['error'] ?></span><?php endif; ?>
                                                            </div>
                                                            <div class="col-sm-1">
                                                                <a class="btn pull-right btn-sm btn-sm-fix btn-danger<?= $auth < 2 ? ' hidden' : '' ?>" id="subject:<?= $fId ?>:loads:<?= $loadsId ?>:delete" href="#"><i class="fa fa-times"></i></a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            <?php endforeach; ?>
                                        </div><!-- /.box-body -->
                                        <div class="box-footer">
                                            <a class="btn btn-default<?= $auth < 2 ? ' hidden' : '' ?>" id="subject:<?= $fId ?>:loads:add" href="#"><i class="fa fa-plus"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->
                <?php endforeach; ?>
            </div><!-- /.box-body -->
            <div class="box-footer">
                <a class="btn btn-default<?= $auth < 2 ? ' hidden' : '' ?>" id="subject:add" href="#">Добавить заявителя</a>
            </div>
        </div><!-- /.box -->
            <!-- Actions Действия -->
            <div class="box-footer">
                <?= $actions['save']['html'] ?>
                <?= $actions['saveexit']['html'] ?>
                <?= $actions['exit']['html'] ?>
            </div>

            <!-- Скрытые поля -->
            <?= $hidden_fields['action']['html'] ?>
        </div
</form>
<div class="modal" id="historyDateModal">
    <div class="modal-dialog">
        <form role="form" method="post" action="<?= $url ?>">
            <div class="modal-content">
                <div class="modal-header">
                    <button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Выбор даты</h4>
                </div>
                <div class="modal-body">
                    <div class="input-group date margin" data-provide="datepicker" data-date-format="dd-mm-yyyy" data-date-clear-btn="true" data-date-language="ru" data-date-today-highlight="true" data-date-autoclose="true">
                        <input type="text" class="form-control" name="time" value="<?= $timestamp?date('d-m-Y',$timestamp):'' ?>"/>
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span></div>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-default pull-left" href="<?= $url ?>">Сбросить</a>
                    <button class="btn btn-primary" type="submit" value="save">Выбрать</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script id="subject-template" type="text/x-handlebars-template">
    <div class="box box-solid box-info" data-id="{{id}}">
        <div class="box-header with-border">
            <h3 class="box-title">Заявитель</h3>
            <div class="box-tools pull-right">
                <a class="btn btn-sm btn-sm-fix btn-info" id="subject:{{id}}:delete" href="#">Удалить</a>
            </div>
        </div><!-- /.box-header -->
        <div class="box-body">

            <div class="form-group form-group-sm <?= 0 == $fieldsets['subject']['template']['fields']['subject_cat']['renderMode'] ? ' hide' : '' ?>">
                <label class="col-sm-4 control-label" for="lic:subject:{{id}}:subject_cat">Категория дисциплины</label>
                <div class="col-sm-8">
                    <?= $fieldsets['subject']['template']['fields']['subject_cat']['html'] ?>
                </div>
            </div>


            <div class="form-group form-group-sm">
                <label class="col-sm-4 control-label">Нагрузка</label>
                <div class="col-sm-8">
                    <div class="box box-solid box-default loads-container" data-lastid="1">
                        <div class="box-body">
                        </div><!-- /.box-body -->
                        <div class="box-footer">
                            <a class="btn btn-default" id="subject:{{id}}:loads:add" data-id="{{id}}" href="#"><i class="fa fa-plus"></i></a>
                        </div>
                    </div><!-- /.box -->
                </div>
            </div>

        </div><!-- /.box-body -->
    </div><!-- /.box -->
</script>
<script id="loads-template" type="text/x-handlebars-template">
    <div class="box box-solid box-default" data-id="{{id}}">
        <div class="box-body">
            <div class="form-group">
                <div class="col-sm-7 <?= 0 == $fieldsets['subject']['template']['fieldsets']['loads']['template']['fields']['period']['renderMode'] ? ' hide' : '' ?>">
                    <?= $fieldsets['subject']['template']['fieldsets']['loads']['template']['fields']['period']['html'] ?>
                </div>
                <div class="col-sm-4<?= 0 == $fieldsets['subject']['template']['fieldsets']['loads']['template']['fields']['bonus']['renderMode'] ? ' hide' : '' ?>">
                    <?= $fieldsets['subject']['template']['fieldsets']['loads']['template']['fields']['bonus']['html'] ?>
                </div>
                <div class="col-sm-1">
                    <a class="btn pull-right btn-sm btn-sm-fix btn-danger" id="subject:{{parentId}}:loads:{{id}}:delete" href="#"><i class="fa fa-times"></i></a>
                </div>
            </div>
        </div>
    </div>
</script>
<script>
    var form = {
        tmplSubject: null,
        tmplBonus: null,
        init: function () {
            var self = this;
            this.tmplSubject = Handlebars.compile($('#subject-template').html());
            this.tmplBonus = Handlebars.compile($('#loads-template').html());
            app.formInitContainer($('div.subject-container'), 'subject', this.tmplSubject, {}, function(id, div) {
                self.formBonusInitContainer(id, $('div.loads-container', div)); // Поощрения
            });

        },
        formBonusInitContainer: function (parentId, div) {
            var self = this;
            $('#subject\\:' + parentId + '\\:loads\\:add', div).click(function () { // активируем кнопку добавить подраздел
                var id = div.data('lastid');
                div.children('div.box-body').append(self.tmplBonus({parentId: parentId, id: id})); // вставить шаблон
                self.formBonusInitSection(parentId, $('div.box[data-id=' + id + ']', div));
                div.data('lastid', id + 1);
                return false;
            });
            // настройка секций
            div.children('div.box-body').children('div.box').each(function (i, e) {
                self.formBonusInitSection(parentId, $(this));
            });
        },
        formBonusInitSection: function (parentId, div) {
            var self = this;
            $('#subject\\:' + parentId + '\\:loads\\:' + div.data('id') + '\\:delete', div).click(app.deleteSectionCallback); // активировать кнопку удалить
            app.activateFormFields(div);
        }
    };
    $().ready(function () {
        form.init();
    });
</script>
<?php if (isset($isValid)): ?>
    <script>
        $(document).ready(function() {
            $('#errormodal').modal() ;
        });
    </script>
<?php endif; ?>

<div id="errormodal" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title" style="text-align:center;"> Запись не сохранена! </h3>
            </div>
            <div class="modal-body">
                <h4 style="color:red; text-align:center;">Не все обязательные поля заполнены корректно.</h4>
                <hr>
                <p style="text-align:center;">* Для сохранения записи заполните поля, выделенные красным цветом, и повторно нажмите кнопку "Сохранить" </p>
            </div>
        </div>
    </div>
</div>