<?php
/* @var $url string */
/* @var $formName string */
/* @var $fields array */
/* @var $fieldsets array */
/* @var $hidden_fields array */
/* @var $actions array */
/* @var $helper_actions array */
/* @var $timestamp int */
/* @var $versionList array */
/* @var $version string */
/* @var $isNew boolean */
?>
<form class="form-horizontal form-compact" role="form" action="<?= $url ?>" name="<?= $formName ?>" method="post">

   <div class="box box-solid box-primary">
      <div class="box-header with-border">
         <h3 class="box-title"><?= $title ?></h3>
          <div class="box-tools pull-right">
              <?= $helper_actions['history']['html'] ?>
          </div><!-- /.box-tools -->
      </div><!-- /.box-header -->
           <div class="box-body">
               <!-- Fields Поля -->
               <?php foreach ($fields as $id => $field): ?>
                   <div class="form-group form-group-sm <?= 0 == $field['renderMode'] ? ' hide' : '' ?><?= $field['error'] ? ' has-error' : '' ?>">
                       <label class="col-sm-4 control-label" for="<?= $field['id'] ?>"><?= $field['label'] ?><?= $field['required'] ? '*' : '' ?></label>
                       <div class="col-sm-8">
                           <?= $field['html'] ?>
                           <?php if ($field['error']): ?><span class="help-block"><?= $field['error'] ?></span><?php endif; ?>
                       </div>
                   </div>
               <?php endforeach;?>
           <!-- Actions Действия -->
           <div class="box-footer">
               <?= $actions['save']['html'] ?>
               <?= $actions['saveexit']['html'] ?>
               <?= $actions['exit']['html'] ?>
           </div>

       <!-- Скрытые поля -->
       <?= $hidden_fields['action']['html'] ?>
            </div>
   </div>
</form>
<?php if (isset($isValid)): ?>
   <script>
      $(document).ready(function() {
         $('#errormodal').modal() ;
      });
   </script>
<?php endif; ?>

<div id="errormodal" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button status="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title" style="text-align:center;"> Запись не сохранена! </h3>
            </div>
            <div class="modal-body">
                <h4 style="color:red; text-align:center;">Не все обязательные поля заполнены корректно.</h4>
                <hr>
                <p style="text-align:center;">* Для сохранения записи заполните поля, выделенные красным цветом, и повторно нажмите кнопку "Сохранить" </p>
            </div>
        </div>
    </div>
</div>