<?php
/* @var $url string */
/* @var $formName string */
/* @var $fields array */
/* @var $fieldsets array */
/* @var $hidden_fields array */
/* @var $actions array */
/* @var $helper_actions array */
/* @var $timestamp int */
/* @var $versionList array */
/* @var $version string */
/* @var $isNew boolean */
?>
<form class="form-horizontal form-compact" role="form" action="<?= $url ?>" name="<?= $formName ?>" method="post">

   <div class="box box-solid box-primary">
      <div class="box-header with-border">
         <h3 class="box-title">Информация о дисциплине</h3>
          <div class="box-tools pull-right">
              <?= $helper_actions['history']['html'] ?>
          </div><!-- /.box-tools -->
      </div><!-- /.box-header -->
           <div class="box-body">

               <div class="form-group form-group-sm <?= 0 == $fields['name']['renderMode'] ? ' hide' : '' ?><?= $fields['name']['error'] ? ' has-error' : '' ?>">
                   <label class="col-sm-4 control-label" for="name"><?= $fields['name']['label'] ?></label>
                   <div class="col-sm-8">
                       <?= $fields['name']['html'] ?>
                       <?php if ($fields['name']['error']): ?><span class="help-block"><?= $fields['name']['error'] ?></span><?php endif; ?>
                   </div>
               </div>
               <div class="form-group form-group-sm <?= 0 == $fields['shortname']['renderMode'] ? ' hide' : '' ?><?= $fields['shortname']['error'] ? ' has-error' : '' ?>">
                   <label class="col-sm-4 control-label" for="shortname"><?= $fields['shortname']['label'] ?></label>
                   <div class="col-sm-8">
                       <?= $fields['shortname']['html'] ?>
                       <?php if ($fields['shortname']['error']): ?><span class="help-block"><?= $fields['shortname']['error'] ?></span><?php endif; ?>
                   </div>
               </div>
               <div class="form-group form-group-sm <?= 0 == $fields['status']['renderMode'] ? ' hide' : '' ?><?= $fields['status']['error'] ? ' has-error' : '' ?>">
                   <label class="col-sm-4 control-label" for="status"><?= $fields['status']['label'] ?></label>
                   <div class="col-sm-8">
                       <?= $fields['status']['html'] ?>
                       <?php if ($fields['status']['error']): ?><span class="help-block"><?= $fields['status']['error'] ?></span><?php endif; ?>
                   </div>
               </div>
               <div class="box box-solid box-info">
                   <div class="box-header with-border">
                       <h3 class="box-title">Атрибуты </h3>
                   </div><!-- /.box-header -->
                   <div class="box-body">

                   </div>
               </div>
           <!-- Actions Действия -->
           <div class="box-footer">
               <?= $actions['save']['html'] ?>
               <?= $actions['saveexit']['html'] ?>
               <?= $actions['exit']['html'] ?>
           </div>

       <!-- Скрытые поля -->
       <?= $hidden_fields['action']['html'] ?>
            </div>
   </div>
</form>
<script status="text/javascript">
   
</script>
<?php if (isset($isValid)): ?>
   <script>
      $(document).ready(function() {
         $('#errormodal').modal() ;
      });
   </script>
<?php endif; ?>

<div id="errormodal" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button status="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title" style="text-align:center;"> Запись не сохранена! </h3>
            </div>
            <div class="modal-body">
                <h4 style="color:red; text-align:center;">Не все обязательные поля заполнены корректно.</h4>
                <hr>
                <p style="text-align:center;">* Для сохранения записи заполните поля, выделенные красным цветом, и повторно нажмите кнопку "Сохранить" </p>
            </div>
        </div>
    </div>
</div>