<?php
/* @var $url string */
/* @var $errorTitle string */
/* @var $readOnly bool */
/* @var $currentStatus string */
/* @var $statusDaysLeft int */
/* @var $statusDaysLeftString string */
/* @var $statusList array */
/* @var $documentList array */
/* @var $statusCommentAllowedList array */
/* @var $statusFileAllowedList array */
/* @var $statusCommentList array */
/* @var $statusPlaceHolderList array */
/* @var $statusHist array */
/* @var $statusColor array */

$iconMap = [
    'sent' => 'fa-clock-o',
    'error' => 'fa-exclamation-circle',
    'delivered' => 'fa-check-circle-o',
];

$statusColorMap = array_reduce($statusColor, function ($result, $item) {
    foreach ($item[0] as $id) {
        $result[$id] = $item[1];
    }
    return $result;
}, []);

?>
<?php if (isset($errorTitle)): ?>
    <div class="alert alert-warning alert-dismissible">
        <button aria-hidden="true" data-dismiss="alert" class="close" type="button">&times;</button>
        <h4><i class="icon fa fa-ban"></i> <?= $errorTitle ?></h4>
        <?= isset($errorMessage) ? $errorMessage : '' ?>
    </div>
<?php endif; ?>
<div class="row">
    <div class="col-md-5">
        <div class="box box-solid box-default">
            <div class="box-header with-border">
                <i class="fa fa-pencil"></i>
                <h3 class="box-title">Изменение статуса</h3>
            </div><!-- /.box-header -->
            <?php if ($readOnly): ?>
                <div class="box-body">
                    <p class="text-center">- нет доступа -</p>
                </div><!-- /.box-body -->
            <?php else: ?>
                <!-- form start -->
                <form role="form" action="<?= $url ?>" enctype="multipart/form-data" method="post">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="sel_status">Текущий статус</label>
                            <p class="form-control-static"><?= $currentStatus ?></p>
                        </div>
                        <?php if ($statusDaysLeft != null): ?>
                            <div class="form-group">
                                <label for="sel_status">Срок смены статуса</label>
                                <?php if ($statusDaysLeft < 0): ?>
                                    <p class="form-control-static text-red text-bold">Просрочка <?= $statusDaysLeftString ?></p>
                                <?php elseif ($statusDaysLeft == 0): ?>
                                    <p class="form-control-static text-orange text-bold">Сегодня</p>
                                <?php else: ?>
                                    <p class="form-control-static">Осталось <?= $statusDaysLeftString ?></p>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                        <div class="form-group">
                            <label for="sel_status">Новый статус</label>
                            <select id="sel_status" name="sel_status" class="form-control"<?= 0 == count($statusList) ? ' disabled' : '' ?>>
                                <?php foreach ($statusList as $k => $v): ?>
                                    <option value="<?= $k ?>" data-color="<?= $statusColorMap[$k] ?? '' ?>"><?= $v ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="sel_comment">Комментарий</label>
                            <textarea id="sel_comment" name="sel_comment" rows="5" class="form-control" maxlength="1400"<?= 0 == count($statusList) ? ' disabled' : '' ?>></textarea>
                        </div>
                        <div class="form-group">
                            <input type="file" name="file" title="Прикрепить файл"<?= 0 == count($statusList) ? ' class="disabled"' : '' ?>><br/>или<br/>
                            <select class="document-list form-control" name="sel_document" lang="ru" style="width: 100%;"<?= 0 == count($statusList) ? ' disabled' : '' ?>>
                                <option></option>
                                <?php foreach ($documentList as $k => $v): ?>
                                    <option value="<?= $k ?>"><?= $v ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div><!-- /.box-body -->
                    <div class="box-footer">
                        <button class="btn btn-info pull-right<?= 0 == count($statusList) ? ' disabled' : '' ?>" type="submit" name="changeStatus" value="1">Отправить</button>
                    </div><!-- /.box-footer -->
                </form>
                <script>
                    var selStatus = $('#sel_status');
                    var selComment = $('#sel_comment');
                    var divComment = selComment.parent('div');
                    var divFile = $('input[name=file]').parent('div');
                    var st_comment_placeholder = {};
                    var st_comment_allowed = [<?= implode(',', $statusCommentAllowedList) ?>];
                    var st_file_allowed = [<?= implode(',', $statusFileAllowedList) ?>];
                    <?= implode("\n", $statusPlaceHolderList) ?>
                    selStatus.change(function () {
                        selComment.attr('placeholder', this.value in st_comment_placeholder ? st_comment_placeholder[this.value] : '');
                        toggleElement(divComment, st_comment_allowed.indexOf(parseInt(this.value)) !== -1);
                        toggleElement(divFile, st_file_allowed.indexOf(parseInt(this.value)) !== -1);
                    });
                    var value = selStatus.val();
                    selComment.attr('placeholder', value in st_comment_placeholder ? st_comment_placeholder[value] : '');
                    toggleElement(divComment, st_comment_allowed.indexOf(parseInt(value)) !== -1);
                    toggleElement(divFile, st_file_allowed.indexOf(parseInt(value)) !== -1);
                    $(".document-list").select2({
                        placeholder: "Выберите документ",
                        allowClear: true,
                        minimumResultsForSearch: "Infinity"
                    });

                    function toggleElement(el, flag) {
                        flag ? el.show() : el.hide();
                    }
                </script>
            <?php endif; ?>
        </div>
    </div>
    <div class="col-md-7">
        <div class="box box-solid box-default">
            <div class="box-header with-border">
                <i class="fa fa-th-list"></i>
                <h3 class="box-title">История статусов</h3>
            </div>
            <div class="box-body">
                <table class="table table-striped table-condensed table-bordered">
                    <tr>
                        <th>Дата</th>
                        <th>Инициатор</th>
                        <th>Статус заказа</th>
                        <th>Статус на ПГУ</th>
                    </tr>
                    <?php foreach ($statusHist as $v): ?>
                        <tr style="background-color: <?= $statusColorMap[$v['statusid']] ?? 'none' ?>;">
                            <td><?= $v['date']; ?></td>
                            <td><?= $v['userName']; ?></td>
                            <td><?= $v['statusName']; ?></td>
                            <td>
                                <?php if (isset($v['pgu'])): ?>
                                    <span class="text-nowrap">
                                        <i class="fa <?= $iconMap[$v['pgu']['status']] ?>" data-toggle="tooltip" title="<?= $v['pgu']['status_message'] ?>"></i>
                                        <?= $v['pgu']['tech_code_name'] ?: 'Сообщение' ?>
                                    </span>
                                    <p><small><?= $v['pgu']['comment'] ?></small></p>
                                    <?= $v['downloadUrl'] ?>
                                    <?= $v['documentUrl'] ?>
                                <?php else: // для старых заявлений ?>
                                    <?php if ($v['note']): ?>
                                        <span class="text-nowrap">
                                            <i class="fa fa-question-circle-o" data-toggle="tooltip" title="Нет информации о взаимодействии с ПГУ"></i>
                                            <small><?= $v['note'] ?></small>
                                        </span>
                                    <?php endif; ?>
                                    <?= $v['downloadUrl'] ?>
                                    <?= $v['documentUrl'] ?>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
                <?php foreach ($statusColor as $v): ?>
                    <div style="margin-top: 15px;">
                        <span style="background-color: <?= $v[1] ?>; border-radius: 20px; padding: 5px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> - <?= $v[2]?>
                    </div>
                <?php endforeach; ?>
            </div><!-- /.box-body -->
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        function formatState(state) {
            if (state.element) {
                const color = state.element.dataset.color;
                if (color) {
                    return $(`<div style="background-color: ${color}">${state.text}</div>`);
                }
                return $(`<div>${state.text}</div>`);
            }
            return state.text;
        };

        $('#sel_status').select2({
            minimumResultsForSearch: Infinity,
            templateResult: formatState
        });
    });
</script>
